[2024-10-10 11:13:29,042 - INFO -             __init__()->189]- Use pytorch device_name: cpu
[2024-10-10 11:13:29,043 - INFO -             __init__()->197]- Load pretrained SentenceTransformer: https://huggingface.co/dangvantuan/vietnamese-embedding
[2024-10-10 11:23:49,647 - INFO -             __init__()->189]- Use pytorch device_name: cpu
[2024-10-10 11:23:49,649 - INFO -             __init__()->197]- Load pretrained SentenceTransformer: https://huggingface.co/dangvantuan/vietnamese-embedding
[2024-10-10 11:25:46,684 - ERROR -                  run()->51]- ERROR RUN SERVICE!
Traceback (most recent call last):
  File "/var/folders/6w/n21p66td2895by94s7yx_2f40000gn/T/ipykernel_5018/2158751223.py", line 39, in run
    df[columns_to_initialize] = None
UnboundLocalError: local variable 'df' referenced before assignment
[2024-10-10 11:26:04,451 - ERROR -                  run()->51]- ERROR RUN SERVICE!
Traceback (most recent call last):
  File "/var/folders/6w/n21p66td2895by94s7yx_2f40000gn/T/ipykernel_5018/3699006697.py", line 39, in run
    df[columns_to_initialize] = None
UnboundLocalError: local variable 'df' referenced before assignment
